require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :osx, '11.0'
prepare_react_native_project!

target 'om-desktop' do
  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
